const types = {
    FETCH_PROFILE: "FETCH_PROFILE",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
    FETCH_PROFILE_ERROR: "FETCH_PROFILE_ERROR",
    FETCH_SUCCESS_RATES: "FETCH_SUCCESS_RATES",
    FETCH_SUCCESS_CONVERSION: "FETCH_SUCCESS_CONVERSION",
    FETCH_INITIAL_RATES: "FETCH_INITIAL_RATES"
};

export default types;